# Generated by Django 4.0.2 on 2022-02-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('agentid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('contactid', models.CharField(max_length=10)),
                ('agentid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agentapp.agent')),
                ('mobileno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=30)),
                ('locname', models.CharField(max_length=40)),
                ('loccity', models.CharField(max_length=10)),
                ('locstate', models.CharField(max_length=40)),
                ('pincode', models.IntegerField(default=False)),
                ('agentloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentapp.agent')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('addressid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=False)),
                ('landmark', models.CharField(max_length=100)),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentapp.agent')),
            ],
        ),
    ]
